env:
  global:
    - CC_TEST_REPORTER_ID=72252a723393f39aa1459395c4ce5b84e55670f07ec5bdc9d2bbff5808d0945d
language: node_js
node_js:
  - 9
cache: yarn
install:
  - yarn
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - yarn clean
  - yarn test
  - ./node_modules/.bin/codecov
after_script:
  - ./cc-test-reporter upload-coverage < coverage/lcov.info
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
