name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install and test
        run: |
          yarn
          yarn test
        env:
          CI: true
  codecov:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: yarn install and build test coverage
        run: |
          yarn
          yarn test --coverage
      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          name: Prefinem
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info
          # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
          # flags: # optional
          # Specify the location of the .codecov.yml config file
          # yml: # optional
  codeclimate:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: yarn install
        run: yarn
      - name: Code Climate
        uses: paambaati/codeclimate-action@v2.3.0
        env:
          CC_TEST_REPORTER_ID: 72252a723393f39aa1459395c4ce5b84e55670f07ec5bdc9d2bbff5808d0945d
        with:
          coverageCommand: yarn test --coverage
          debug: true
